// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs9SjLp_GU1r2508FU2C3HAsz1qtfQzVU',
    appId: '1:941062322716:web:f4197fe92fc010015d7dd9',
    messagingSenderId: '941062322716',
    projectId: 'fir-d3e54',
    authDomain: 'fir-d3e54.firebaseapp.com',
    storageBucket: 'fir-d3e54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDrAYYyZecgWFsqZvopWICb5eFyRR3ns',
    appId: '1:941062322716:android:7086479ab37f3ec25d7dd9',
    messagingSenderId: '941062322716',
    projectId: 'fir-d3e54',
    storageBucket: 'fir-d3e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-By1YS_D0Ov7F9WmJd6a-xOnNcAnnPY',
    appId: '1:941062322716:ios:35a5810c5c0877e95d7dd9',
    messagingSenderId: '941062322716',
    projectId: 'fir-d3e54',
    storageBucket: 'fir-d3e54.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-By1YS_D0Ov7F9WmJd6a-xOnNcAnnPY',
    appId: '1:941062322716:ios:35a5810c5c0877e95d7dd9',
    messagingSenderId: '941062322716',
    projectId: 'fir-d3e54',
    storageBucket: 'fir-d3e54.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs9SjLp_GU1r2508FU2C3HAsz1qtfQzVU',
    appId: '1:941062322716:web:c263a7b30662faa25d7dd9',
    messagingSenderId: '941062322716',
    projectId: 'fir-d3e54',
    authDomain: 'fir-d3e54.firebaseapp.com',
    storageBucket: 'fir-d3e54.appspot.com',
  );
}
